### ISSUE TITLE
Sanitize path handling

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#106]
The path argument for clone needs an absolute path, else it runs from the path in which the Gooey was invoked from. On Windows, it might be invoked from System32 when a user starts it from the explorer. At the same time, the path selector helpers are not 100% intuitive either, because they allow selecting pre-existing folders and files and thus still require manual editing. Thus one can easily cause an error (trying to clone into a OS root directory with insufficient permissions or a preexisting non-empty directory), or accidentally clone into the wrong place.

**Comment by mih** [comment]
I think this is not just about `clone`, but rather any path-type argument. I was under the impression that we already had an issue on this, but it seems not. Let's use this one. Here is what I think:

The path selection widget must report absolute paths, always. Relative paths only make sense in the presence of a dataset. `dataladcmd_exec` detects that and produces a corresponding `Dataset` instance to make this work. However, this is more of a life-insurance thing than a plan. In general the path input widget is only aware of a preset `dataset` argument, and not of anything that is subsequently happening in the parameter input form. At the same time, absolute paths work just fine under all circumstances. Any of the path selection dialogs already return absolute paths. Consequently, it makes sense to always work with absolute paths when reporting back from `PathParamWidget`.

This also means that globs of paths must also support absolute paths (https://github.com/datalad/datalad-gooey/issues/58).

We need to think about, if/how we can turn manually entered relative paths into absolute ones. It would be a rare "coincidence" whenever the CWD of the GUI app matches the conceptual working directory of a user. It could only ever match for users that have started the GUI in a particular directory. This pretty much means terminal users -- not the primary target audience.

Alternatively, we can pick up on an idea expressed in #116, namely the root item in the tree having particular significance, and use its path to convert any relative paths into absolute ones. This would be less convenient for any "dataset-method"-type command configurations, but make more (intuitive) sense in general.

It would also work nicely in the documentation. Rather than having lots of complex condition sets, it would be

> Any relative path is relative to the root item of the filesystem browser.

**Comment by bpoldrack** [comment]
> This would be less convenient for any "dataset-method"-type command configurations, but make more (intuitive) sense in general.

From my POV, it woud be a bit more intuitive if in case of a dataset method, a relative path is relative to that dataset. The user clicked on a particular dataset in the tree view and thereby set it as the context to get there after all. Take for example a `save`. I right click on a dataset and then I would need to give a bunch of paths and either manually click through the path selectors over and over or type lengthy paths.
Being able to give a relative path to the dataset could be much more convenient.

**Comment by mih** [comment]
If that would be the case, we would need to enshrine that setting a `dataset` argument value for the configuration widget can not be reset. The form only knows what argument value have been set before its startup. It can only support between-parameter-widget interactions based on this information.

From the Gooey POV there is no "case of a dataset method" -- there is only the case where we decide to consider a dataset argument value a fixed reference or not. If we would ever allow editing the reference, we would somehow need to ensure that all other argument values are reset, because the semantics of the configuration have changed. Such behavior seems to have numerous corner cases.

**Comment by mih** [comment]
FTR: This issue is not relevant for the MVP release. Manual path entry will not be supported.

**Comment by adswa** [comment]
One (maybe overly specific thing) that bugs me about path selection is that it is invoked from CWD instead of the "root" directory selected or provided at path startup. You can see in the screenshot below how I specifically select a directory (``/home/adina/containers``) to open, but the path selection pickers starts from where I invoked the ``datalad gooey`` command from:
![gooeypaths](https://user-images.githubusercontent.com/29738718/190980671-05c4fa97-0970-456d-b514-939fee3bfbe6.gif)

That's probably confusing when people aren't used to navigate much in their filesystem, and especially on Windows, where it will start path selection from System32. 

I tried to pass the initially selected/passed path through the app to use as a basedir for the Directory picker, but failed so far. Alternatively, we could maybe have the path selection start in a users Home directory by default (instead of using CWD as a default).

**Comment by mih** [comment]
@adswa I will provide a patch for that

**Comment by adswa** [comment]
I think much that was unearthed in this issue has been improved. I'm inclined to close this, but please reopen if anyone finds something that is yet unaddressed.
