### ISSUE TITLE
Type annotation changes once state is annotated

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#134]
Testing the latest version on a Mac. Many items are first indicated as being a symlink, with the icon being the one associated with a symlink. The state annotation process takes a second or so longer (depending on the amount of items being annotated). Once the state is annotated, the item type also changes from symlink to file, and the icon changes as well. This seems confusing.

E.g.:

https://user-images.githubusercontent.com/10141237/190975457-eeb55a42-51b6-4bec-80bd-087b3b044c8d.mov

**Comment by mih** [comment]
I agree that it can be confusing, but I also think users will quickly accept this as normal behavior.

This is because the type of an item cannot be fully known until after full annotation (e.g. a symlink could be that, or an annexed file). The initial exploration aims to be as fast as possible, to give users immediate feedback on their actions. If we make this initial status exploration do full annotation, we add a substantial delay to that first feedback.

We could also decide to not show any information that may change later on. In that case, users could not work with items until their type is fully determined, adding the delay before a potential user interaction.

In any case, removing this confusion means making the user wait longer, for one or another aspect.

**Comment by mslw** [comment]
I noticed the same on GNU/Linux (so not os-specific), but quickly brushed it off as something that simply needs a moment to update as things are listed, so +1 on:
> I agree that it can be confusing, but I also think users will quickly accept this as normal behavior.

**Comment by mih** [comment]
We can also look into shortening the interval when annotations would be kicked off. But for now this is good enough, I think. Closing.
