### ISSUE TITLE
NF: Ability to kill a command

### ISSUE THREAD

**Issue by jsheunis** [datalad/datalad-gooey#31]
I want to be able to "hit CTRL-C" if a command takes too long to run or for whatever other reason.

**Comment by loj** [comment]
I also had the desire for such a thing.

**Comment by mih** [comment]
So this turns out to be tricky. Unlike a `ProcessPool` executor, it is not possible to terminate a `ThreadPool` or even individual workers in them.

According to https://www.geeksforgeeks.org/python-different-ways-to-kill-a-thread/ the approach would be to have `_cmdexec_thread()` inspect a per-thread kill-switch  after each received result, and raise a dedicated exception (thereby terminating the thread).

Terminating all commands, as asked in #38, means removing all futures that have not activated yet, and setting the kill-switch on all others.

Access to the kill-switches needs to be therad-safe, hence we should only make them so and so often, to avoid unnecessary slowdown, should we decide to have many thread running (not the case right now).
