### ISSUE TITLE
Create a Windows-type installer 

### ISSUE THREAD

**Issue by adswa** [datalad/datalad-gooey#83]
A non-terminal-based installation method that matches the typical install-software-under-windows experience

**Comment by christian-monch** [comment]
Will have a look at it.

**Comment by adswa** [comment]
Maybe its also worth looking into https://github.com/mne-tools/mne-installers for inspiration? It looks like the MNE team has set up a system to create installers for all platforms at once.

**Comment by christian-monch** [comment]
> Maybe its also worth looking into https://github.com/mne-tools/mne-installers for inspiration? It looks like the MNE team has set up a system to create installers for all platforms at once.

Great, thanks. Will look into it.

**Comment by adswa** [comment]
I also just stumbled across https://www.pythonguis.com/tutorials/packaging-pyside6-applications-windows-pyinstaller-installforge/

**Comment by mih** [comment]
I think psychopy had a complete installer (with Python and everything), particularly targeting an all-in-one package

**Comment by christian-monch** [comment]
# Datalad Gooey Installer for Windows

Let me present the first version of the windows installer. Some properties:

- it comes with embedded python 3.9,
- it comes with git- and git-annex installers.
- it requires network access to complete the installation
- it always installs in %LOCALAPPDATA%\Programs\datalad\datalad_gooey
- it does not provide an uninstaller (but does not write into the registry, so uninstalling can easily done be deleting the app dir)
- it creates a shortcut to datalad_gooey on the desktop

Feel free to test it. If you have git and git-annex already installed, just quit the git and git-annex installers when they are executed. After a few seconds, you should get a nice datalad gooey shortcut on your desktop.

If you don't have git and git-annex installed yet, you are on your own! ;-)  I have not testes this scenario yet, so I don't know whether you can just run the installers one by one and be done with it, or whether there needs to be a reboot in between. Feel free to test that and get back to me (while I am looking for the best way to quickly get back to a fresh windows installation in order to test the scenario myself). 

Some more information. The code currently resides here (https://github.com/christian-monch/datalad-gooey-windows-installer), it uses Nullsoft's Installer Script (NIS) tools.

**Comment by adswa** [comment]
I can try, but what is the exact process? I would need to compile the NSI file?

**Comment by christian-monch** [comment]
> I can try, but what is the exact process? I would need to compile the NSI file?

Just use the installer that I uploaded in matrix (cannot attach it here because it is too large, and did not want to stuff it into the repo)

**Comment by adswa** [comment]
I tried with the second version of the installer, on a System I wiped free of Python, DataLad, git, git-annex. Here are the observations:

- I downloaded the .exe from juseless and started it from a cmd - no microsoft defender warning!
- The first dialog after the installer wizard is the complete git setup dialog, with all possible git customizing steps (nice). We should add information on this in the docs, though, as the selection can be quite overwhelming, involving default editors (vim), default branch names, choosing SSH executable, SSL, whether or not to enable symbolic links ... maybe a "you can usually stick to the defaults of Git's setup" is sufficient, but some non-defaults of the current setup definitely would make sense (e.g., not choose vim, enable symbolic links).
- After Git is installed, the installer smoothly proceeds to git-annex, with only two user dialogs, and super swift installtion
- the remainder of the installation is only the progress bar of the wizard (nice)
- The installation process overall takes quite a while because of the lengthy git-installation process, all other steps are fast
- after the installation, I have  a functional desktop shortcut and explorer icon.

Everything in the installation seems nicely isolated, e.g., Python is not available outside of the app, and neither is datalad. Only git and git-annex are available outside of the app.

Importantly, and sadly, with only the installer, the **App crashes** when I use the path picker as described in #114. I reinstalled the c++ library in hopes of a fix, but the crash persisted. I uninstalled (i.e, removed the directory (which was a bit hard to find, we should document this probably)), and reinstalled, but **no success** so far.

But when I reinstalled Python (Python 10) and datalad (0.17.6) and datalad-gooey (-e .) in a fresh virtual environment on top of 36f47a092 the crash did not happen, only the "i need to click twice on the path picker" that @Manukapp reported elsewhere. I'm a bit clueless as for why.

**Comment by mslw** [comment]
Can confirm a successful installation, and a very similar process to that described by @adswa above (with the only difference that I double-clicked the installer, so I had to allow Windows Defender exception and confirm the installation).

One thing that came up was that a warning about not having git user name and e-mail is presented in the command line window, and should rather be shown by the app itself (known issue #147). I set that through git bash and restarted the app.

Unfortunately I also had the crash with file picker described in #114 .
