### ISSUE TITLE
Dedicated support for commit (and other) messages

### ISSUE THREAD

**Issue by mih** [datalad/datalad-gooey#93]
Right now the Parameter only says `EnsureStr() | EnsureNone()`, but a multiline edit widget is the more suitable choice IMHO.

A specific widget can be selected based on the parameter name `message`.

Related:

```
message_file_opt = Parameter(
    args=("-F", "--message-file"),
    doc="""take the commit message from this file. This flag is
    mutually exclusive with -m.""",
    constraints=EnsureStr() | EnsureNone())
```

Based on this definition, it would not be possible to know that a path select is needed.

Moreover, both options are mutually exclusive, so it would make sense to handle them both together. Maybe have a "File Open" button that actually loads a message from file and passes it on to `--message` as a `str`. Even whether or not a command supports both.

**Comment by bpoldrack** [comment]
Implemented multi line edit for `message`. Drag&Drop behavior ATM: You grab a text from some editor and drop it in. If a file is dropped from file manager I currently get its `file:` URL as text in the editor. I am not sure whether is would be desirable to change that, so that we actually read such file's content. Both may be useful. What would be the expectation of a drag&drop user?
